version: "3.4"

services:
  adoptium-openjdk:
    container_name: adoptium-openjdk-test
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      args:
        - openjdk_download_url=https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
        - openjdk_extracted_folder_name=jdk-17.0.1+12
        - openjdk_final_folder_name=adoptium-temurin-17
